import { useAuthStore } from "@/libs/store";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { DefaultLayout } from "@/components/Layout";
import { Theme } from "@radix-ui/themes";
import { getData } from "@/libs/fetchData";
import { fetchSuccess } from "@/libs/helper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Nunito({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { setUser } = useAuthStore.getState();
  const { status, data, error } = await getData({ endpoint: "/me" });
  if (fetchSuccess(status)) {
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#fbfaf8] antialiased`}
      >
        <div className="">
          <Theme>
            <DefaultLayout>{children}</DefaultLayout>
          </Theme>
        </div>
      </body>
    </html>
  );
}
